### ISSUE TITLE
Sections inside tabs are not showing up

### ISSUE THREAD

**Issue by Luc45** [NateWr/simple-admin-pages#16]
Hi, first of all, thanks for this open-source library, it's awesome and very necessary.

I am facing an issue while trying to use tabbed sections. I have this code:

```
// Basic settings tab
$this->sap->add_section(
    'very-simple-password',
    [
        'id'            => 'basic-settings',
        'title'         => __('Basic Settings', 'very-simple-password'),
        'description'   => '',
        'is_tab'	=> true,
    ]
);

// "Customization" section
$this->sap->add_section(
    'very-simple-password',
    [
        'id'           => 'customization',
        'title'        => __( 'Customization', 'very-simple-password' ),
        'description'  => '',
        'tab'          => 'basic-settings',
    ]
);
```

However, a "Basic Section" tab does not show, neither the "Customization" section inside of it.

The actual code contains two tabs and a few sections, and can be seen here: https://pastebin.com/91DPBAg2

Using PHP Storm debugging tools, I see that AdminPageSection.class.php::get_page_slug() returns the expected values both for the tab and for the sections inside the tab. That means that the "Basic Settings" tab returns an ID of "very-simple-password", which is the page, and the "Customization" section inside Basic Settings tab returns "basic-settings", which is the tab ID, which is expected.

I don't know why this is not working. Can you please take a quick look at the code and help me out?

Thanks!

**Comment by NateWr** [comment]
I've had a look at your code and at first glance I can't spot anything wrong with it. Are some of the fields showing correctly but not all of them?

If you want you can pick through [my code](https://github.com/NateWr/restaurant-reservations/blob/master/includes/Settings.class.php#L219) for sections nested in tabs.

**Comment by Luc45** [comment]
Hey buddy, I know it sounds kinda crazy, but if you'd help me debug it in Google Hangouts or Teamviewer it would be awesome?

**Comment by Luc45** [comment]
I got it. My `add_page()` args was lacking `default_tab` key, which caused nothing to show up.

```
$this->sap->add_page(
    'options',
    [
        'id'			=> $this->slug,
        'title'			=> __('Very Simple Password', 'very-simple-password'),
        'menu_title'	=> __('Very Simple Password', 'very-simple-password'),
        'description'	=> '',
        'capability'	=> 'manage_options',
        'default_tab'   => 'basic-settings',
    ]
);
```

**Comment by Luc45** [comment]
PS: Might be a good idea to mention this in the docs :)
